name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: ubuntu-latest
            name: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            name: aarch64-unknown-linux-musl
          - os: macos-13
            name: x86_64-apple-darwin
          - os: macos-latest
            name: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Install musl-tools on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
        if: contains(matrix.target.name, 'musl')
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target.name }}
          args: "--locked --release"
          strip: true
      - run: mv target/${{ matrix.target.name }}/release reconnect-${{ matrix.target.name }}
      - name: Publish to releases
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: "reconnect-*"
