name: Release

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        - os: ubuntu-latest
          target: x86_64-unknown-linux-musl
        - os: ubuntu-latest
          target: aarch64-unknown-linux-musl
        - os: macos-13
          target: x86_64-apple-darwin
        - os: macos-latest
          target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Install musl-tools on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
        if: contains(matrix.target, 'musl')
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true
      - run: mv target/${{ matrix.target }}/release reconnect-${{ matrix.target }}
      - name: Publish to releases
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: "reconnect-*"
        if: startsWith(github.ref, 'refs/tags/v')
